branchName: "GH-${issue.number}-${issue.title,}"
autoCloseIssue: true
gitSafeReplacementChar: "-"
branches:
  - label: bug
    prefix: hotfix/
  - label: content
    prefix: hotfix/
  - label: dependencies
    prefix: hotfix/
  - label: enhancement
    prefix: feature/
  - label: "*"
    skip: true
