# Upstream to abstract backend connection(s) for php
upstream php {
    server unix:/var/run/php-fpm.sock;
}

server {
    listen 80;
    listen [::]:80;
    server_name cardalmanac.com;

    #return 301 https://$host$request_uri;

    include /etc/nginx/conf.d/server/*.conf;
}

#server {
#    listen 443 ssl default_server;
#    listen [::]:443;

#    ssl_certificate /etc/letsencrypt/live/cardalmanac.com/fullchain.pem;
#    ssl_certificate_key /etc/letsencrypt/live/cardalmanac.com/privkey.pem;

#    server_name cardalmanac.com;

#    include /etc/letsencrypt/options-ssl-nginx.conf;
#    include /etc/nginx/conf.d/server/*.conf;
}
