version: '3.7'

services:
    admin:
        volumes:
            - ../:/var/www/app

    mysql:
        volumes:
            - "${DOCKER_VOLUME_MYSQL_STORAGE:-../.docker/storage/dusk/}:/var/lib/mysql"
