version: '3.7'

services:

    caapp:
        image: picklewagon/cardalmanac-app:${DOCKER_TAG_CAAPP:-latest}
        entrypoint: /var/www/app/.docker/scripts/update.entrypoint.sh
        command: ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
        environment:
            APP_DEBUG: "false"
            APP_ENV: production
            APP_KEY: "base64:+dkZjG9FPdJfNH9GGG9xeq2+2Z5pgmp6XiEQW/aFwY8="
            APP_LOG_LEVEL: error
            APP_URL: https://cardalmanac.com
            NODE_ENV: production
            PHP_OPCACHE_ENABLE: 1
        working_dir: /var/www/app
        volumes:
            - /var/www/cardalmanac.com/storage:/var/www/app/storage:delegated
            - /var/www/cardalmanac.com/certs:/etc/letsencrypt
        ports:
            - "80:80"
            - "443:443"
        networks:
            - overlay
        healthcheck:
            test: curl -fk https://localhost/ping
            interval: 1m
            timeout: 3s
            retries: 30
            start_period: 30s

networks:
    overlay:
