version: '3.7'

services:
    admin:
        image: picklewagon/tradingcardapi-admin:${DOCKER_TAG_ADMIN:-latest}
        volumes:
            # Mount the build directory to get unit test results easily
            - ../build:/var/www/app/build
        env_file:
            - ../.env.local
        environment:
            # Override these environment variables
            APP_ENV: testing
            CACHE_DRIVER: array
            CARDS_CONNECTION: test_sqlite
            DB_CONNECTION: test_sqlite
            QUEUE_DB_CONNECTION: test_sqlite
            QUEUE_DRIVER: sync
            SESSION_DRIVER: array
        entrypoint: /var/www/app/.docker/scripts/tests.entrypoint.sh
        command: ["phpunit"]
