name: Build and Test

on:
  pull_request:

jobs:
  testing:
    name: Build Docker Container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build container
        run: docker-compose up -d --build
      - name: Terminate container
        run: docker-compose down
