name: Deploy

on:
  deployment:

env:
  SERVICE_NAME: cardalmanac-app
  VERSION: ${{ github.event.deployment.ref }}

jobs:
  docker-tag-latest:
    name: Tag docker image
    runs-on: ubuntu-latest
    steps:
      - uses: avakar/set-deployment-status@v1
        name: "Deployment: In Progress"
        with:
          deployment_id: ${{ github.event.deployment.id }}
          state: in_progress
          log_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.CARDALMANAC_APP_TOKEN }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - env:
          NEW_TAG: latest
        run: |
          docker pull picklewagon/${SERVICE_NAME:?}:${VERSION:?}
          docker tag picklewagon/${SERVICE_NAME}:${VERSION} picklewagon/${SERVICE_NAME}:${NEW_TAG}
          docker push picklewagon/${SERVICE_NAME}:${NEW_TAG}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: docker-tag-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Create environment file
        run: |
          echo "TRADINGCARDAPI_CLIENT_ID=${{ secrets.TRADINGCARDAPI_CLIENT_ID }}" > cardalmanac.env
          echo "TRADINGCARDAPI_CLIENT_SECRET=${{ secrets.TRADINGCARDAPI_CLIENT_SECRET }}" >> cardalmanac.env
          echo "APP_KEY=${{ secrets.APP_KEY }}" >> cardalmanac.env
      - name: Deploy server
        id: deploy_server
        run: .docker/scripts/create-host.sh ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} cardalmanac
      - name: Upload deploy files
        uses: appleboy/scp-action@master
        with:
          #host: //${{ steps.deploy_server.outputs.ip_address }}
          host: cardalmanac.com
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          rm: true
          timeout: 60s
          source: ".docker/scripts/deploy.sh, .docker/prod.docker-compose.yaml, cardalmanac.env"
          target: "~/deploy/"
      - name: Deploy site
        uses: appleboy/ssh-action@master
        env:
          APP_KEY: ${{ secrets.APP_KEY }}
          TRADINGCARDAPI_CLIENT_ID: ${{ secrets.TRADINGCARDAPI_CLIENT_ID }}
          TRADINGCARDAPI_CLIENT_SECRET: ${{ secrets.TRADINGCARDAPI_CLIENT_SECRET }}
        with:
          #host: ${{ steps.deploy_server.outputs.ip_address }}
          host: cardalmanac.com
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          envs: APP_KEY,TRADINGCARDAPI_CLIENT_ID,TRADINGCARDAPI_CLIENT_SECRET
          script: |
            export APP_KEY=$APP_KEY
            export TRADINGCARDAPI_CLIENT_ID=$TRADINGCARDAPI_CLIENT_ID
            export TRADINGCARDAPI_CLIENT_SECRET=$TRADINGCARDAPI_CLIENT_SECRET
            ~/deploy/.docker/scripts/deploy.sh
      - uses: avakar/set-deployment-status@v1
        name: "Deployment: Failed"
        if: failure()
        with:
          deployment_id: ${{ github.event.deployment.id }}
          state: failure
          log_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.CARDALMANAC_APP_TOKEN }}
      - uses: avakar/set-deployment-status@v1
        name: "Deployment: Success"
        if: success()
        with:
          deployment_id: ${{ github.event.deployment.id }}
          state: success
          log_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.CARDALMANAC_APP_TOKEN }}
